apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  name: stacktrace-analyzer-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/stacktrace-analyzer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PYTHONPATH
          value: "/app"
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 10
